name: verify-pr-state
description: Test PR Verification State

inputs:
  jobs:
    description: 'Jobs to validate'
    required: false
    default: '[]'

runs:
  using: composite
  steps:
    - name: Install additional tools
      shell: bash
      run: |
        apt update && apt install -y jq

    - name: Iterate through array
      shell: bash
      run: |
        while IFS= read -r item; do
          name=$(echo "$item" | jq -r '.name')
          result=$(echo "$item" | jq -r '.result')

          echo "job=$name result is $result"
          if [[ "$result" == "failure" ]] || [[ "$result" == "cancelled" ]]; then
            echo "::error:: Merge prohibited. '$name' job result is '$result'"
            exit 1
          fi
        done < <(echo '${{ inputs.jobs }}' | jq -c '.[]')
