name: PR verification

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  sonar_scan_verification:
    name: Sonar-scan
    uses: ./.github/workflows/sonar-scan.yml
    secrets: inherit

  test_pipeline_state:
    if: always()
    needs: [
        sonar_scan_verification
    ]
    name: Test PR Verification State
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test Pipeline State
        id: jobs_result
        shell: bash
        run: |
          to_check='[
            { "name" : "sonar_scan", "result": "${{ needs.sonar_scan_verification.result }}" }
          ]'

          formatted=$(echo "$to_check" | jq -c '.')
          echo "result=$formatted" >> $GITHUB_OUTPUT
      
      - name: Validate Jobs
        uses: ./.github/actions/verify-pr-state
        with:
          jobs: '${{ steps.jobs_result.outputs.result }}'
